export const safelistClasses = [
	'bg-blue-100',
	'text-blue-800',
	'bg-red-100',
	'text-red-800',
	'bg-pink-100',
	'text-pink-800',
	'bg-purple-100',
	'text-purple-800',
	'bg-rose-100',
	'text-rose-800',
	'bg-amber-100',
	'text-amber-800',
	'bg-green-100',
	'text-green-800',
	'bg-indigo-100',
	'text-indigo-800',
	'bg-gray-100',
	'text-gray-800',
	'bg-gray-200',
	'bg-neutral-100',
	'text-neutral-800',
	'!bg-blue-100',
	'!bg-red-100',
	'!bg-pink-100',
	'!bg-purple-100',
	'!bg-rose-100',
	'!bg-amber-100',
	'!bg-green-100',
	'!bg-indigo-100',
	'!bg-gray-100',
	'!bg-gray-200',
	'!bg-yellow-100',
	'!bg-neutral-100',

	// Priority colors
	'bg-yellow-100',
	'text-yellow-800',

	// Status colors (overlaps with above, but kept for clarity)
	'bg-gray-200',
	'text-gray-800',
	'bg-yellow-100',
	'text-yellow-800',
	'bg-green-100',
	'text-green-800',

	// Icons (all Lucide icons used in constants)
	'i-lucide:bed',
	'i-lucide:utensils',
	'i-lucide:sparkles',
	'i-lucide:music',
	'i-lucide:palette',
	'i-lucide:file-text',
	'i-lucide:camera',
	'i-lucide:map-pin',
	'i-lucide:more-horizontal',
	'i-lucide:arrow-down',
	'i-lucide:arrow-right',
	'i-lucide:arrow-up',
	'i-lucide:alarm-clock-minus',
	'i-lucide:alarm-clock',
	'i-lucide:alarm-clock-check',
	'i-lucide:minus',

	// Common layout classes used in components
	'inline-flex',
	'items-center',
	'rounded-md',
	'px-2',
	'py-1',
	'text-xs',
	'gap-2',
	'font-medium',
	'w-3',
	'h-3',
	'w-4',
	'h-4',
];

